#!/usr/bin/env python3
# 2026/05/20 coded by codex and okazaki,i
# 2026/05/21 modified by codex and okazaki,i

import re
import sys
import os
import stat
import unicodedata

DEFAULT_LIMIT = 100

ansi_re = re.compile(r'\x1b\[[0-9;]*m')


def _char_width(ch):
    if unicodedata.east_asian_width(ch) in ('F', 'W', 'A'):
        return 2
    return 1


def _is_pipe_or_tty_stdout():
    if sys.stdout.isatty():
        return True

    try:
        mode = os.fstat(sys.stdout.fileno()).st_mode
    except OSError:
        return False

    return stat.S_ISFIFO(mode)


def _get_terminal_columns_from_stream(stream):
    try:
        columns = os.get_terminal_size(stream.fileno()).columns
    except (AttributeError, OSError):
        return None

    if columns <= 0:
        return None

    return columns


def _get_terminal_columns_from_tty():
    try:
        tty = os.open('/dev/tty', os.O_RDONLY)
    except OSError:
        return None

    try:
        columns = os.get_terminal_size(tty).columns
    except OSError:
        return None
    finally:
        os.close(tty)

    if columns <= 0:
        return None

    return columns


def _get_terminal_columns_from_environment():
    try:
        columns = int(os.environ.get('COLUMNS', ''))
    except ValueError:
        return None

    if columns <= 0:
        return None

    return columns


def _get_default_limit():
    for stream in (sys.stdout, sys.stderr, sys.stdin):
        columns = _get_terminal_columns_from_stream(stream)
        if columns is not None:
            return columns

    columns = _get_terminal_columns_from_tty()
    if columns is not None:
        return columns

    columns = _get_terminal_columns_from_environment()
    if columns is not None:
        return columns

    return DEFAULT_LIMIT


def _parse_positive_int(value, option_name):
    try:
        number = int(value)
    except ValueError:
        print(f"mycut: invalid value for {option_name}: '{value}'", file=sys.stderr)
        sys.exit(2)

    if number <= 0:
        print(f"mycut: invalid value for {option_name}: '{value}'", file=sys.stderr)
        sys.exit(2)

    return number


def _parse_options(argv):
    color_mode = 'auto'
    limit = _get_default_limit()
    i = 0

    while i < len(argv):
        arg = argv[i]

        if arg.startswith('--color='):
            value = arg.split('=', 1)[1]
            if value not in ('auto', 'never', 'always'):
                print(f"mycut: invalid argument for --color: '{value}'", file=sys.stderr)
                sys.exit(2)
            color_mode = value
        elif arg == '-c' or arg == '--characters':
            i += 1
            if i >= len(argv):
                print(f"mycut: option requires an argument -- '{arg}'", file=sys.stderr)
                sys.exit(2)
            limit = _parse_positive_int(argv[i], arg)
        elif arg.startswith('--characters='):
            value = arg.split('=', 1)[1]
            limit = _parse_positive_int(value, '--characters')
        else:
            print('usage: mycut [--color=auto|never|always] [-c N|--characters N|--characters=N]', file=sys.stderr)
            sys.exit(2)

        i += 1

    return color_mode, limit


color_mode, limit = _parse_options(sys.argv[1:])

if color_mode == 'always':
    keep_color = True
elif color_mode == 'never':
    keep_color = False
else:
    keep_color = _is_pipe_or_tty_stdout()

for line in sys.stdin:
    had_newline = line.endswith('\n')
    content = line[:-1] if had_newline else line

    pos = 0
    visible = 0
    out = ""

    while pos < len(content) and visible < limit:
        m = ansi_re.match(content, pos)

        if m:
            if keep_color:
                out += m.group(0)
            pos = m.end()
        else:
            ch = content[pos]
            width = _char_width(ch)
            if visible + width > limit:
                break
            out += ch
            pos += 1
            visible += width

    if keep_color:
        out += "\x1b[0m"

    if had_newline:
        out += '\n'

    sys.stdout.write(out)
