#!/usr/bin/env python3
import sys
import re

LIMIT = 100

ansi_re = re.compile(r'\x1b\[[0-9;]*m')

for line in sys.stdin:
    pos = 0
    visible = 0
    out = ""

    while pos < len(line) and visible < LIMIT:
        m = ansi_re.match(line, pos)

        if m:
            out += m.group(0)
            pos = m.end()
        else:
            out += line[pos]
            pos += 1
            visible += 1

    out += "\x1b[0m"
    print(out)
