#!/usr/bin/env python3
# 2026/05/20 coded by codex

import re
import sys
import os
import stat

LIMIT = 100

ansi_re = re.compile(r'\x1b\[[0-9;]*m')


def _is_pipe_or_tty_stdout():
    if sys.stdout.isatty():
        return True

    try:
        mode = os.fstat(sys.stdout.fileno()).st_mode
    except OSError:
        return False

    return stat.S_ISFIFO(mode)


def _parse_color_mode(argv):
    mode = 'auto'
    rest = []
    for arg in argv:
        if arg.startswith('--color='):
            value = arg.split('=', 1)[1]
            if value not in ('auto', 'never', 'always'):
                print(f"mycut: invalid argument for --color: '{value}'", file=sys.stderr)
                sys.exit(2)
            mode = value
        else:
            rest.append(arg)
    return mode, rest


color_mode, args = _parse_color_mode(sys.argv[1:])
if args:
    print('usage: mycut [--color=auto|never|always]', file=sys.stderr)
    sys.exit(2)

if color_mode == 'always':
    keep_color = True
elif color_mode == 'never':
    keep_color = False
else:
    keep_color = _is_pipe_or_tty_stdout()

for line in sys.stdin:
    had_newline = line.endswith('\n')
    content = line[:-1] if had_newline else line

    pos = 0
    visible = 0
    out = ""

    while pos < len(content) and visible < LIMIT:
        m = ansi_re.match(content, pos)

        if m:
            if keep_color:
                out += m.group(0)
            pos = m.end()
        else:
            out += content[pos]
            pos += 1
            visible += 1

    if keep_color:
        out += "\x1b[0m"

    if had_newline:
        out += '\n'

    sys.stdout.write(out)
